version: 0.0
os: linux
files:
  - source: /webroot
    destination: /var/www/html/
hooks:
    BeforeInstall:
        - location: infra/install_dependencies
          timeout: 300
          runas: root
        - location: infra/start_server
          timeout: 300
          runas: root
    ApplicationStop:
        - location: infra/stop_server
          timeout: 300
          runas: root
